version: 2
updates: 
# Shared projects
  - package-ecosystem: "nuget"
    # Look for NuGet dependency info from the `Api Gateway` directory
    directory: "/RealEstate.ApiGateway" 
    # Check the nuget registry for updates weekly: 
    interval: "weekly"
   
  - package-ecosystem: "nuget"
    directory: "/RealEstate.Shared" 
    interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/RealEstate.Test" 
    interval: "weekly"
  
# Microservice projects
  - package-ecosystem: "nuget"
    directory: "/Microservices.ClientsMicroservice" 
    interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/Microservices.ContractsMicroservice" 
    interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/Microservices.EstatesMicroservice" 
    interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/Microservices.ExternalAPIsMicroservice" 
    interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/Microservices.ListingsMicroservice" 
    interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/Microservices.MessagingMicroservice" 
    interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/Microservices.UtilitiesMicroservice" 
    interval: "weekly"

# Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
