version: '3.4'


networks:
  backend:
    driver: bridge
  frontend: 
    driver: bridge


services:
  realestate.api:
    container_name: api-gateway
    image: ${DOCKER_REGISTRY-}realestateapi
    build:
      context: .
      dockerfile: RealEstate.Api/Dockerfile
    ports:
      - 8001:80
    networks: 
      - backend, frontend 

# ESTATE MICROSERVICE
  estate-webapi:
    container_name: estate-webapi
    image: ${DOCKER_REGISTRY-}estateWebAPI
    build:
      context: .
      dockerfile: RealEstate.Api/Dockerfile #fix dir
    networks: 
      - backend 
    environment: 
      - DB_HOST=estatedb
      - DB_NAME=estates
      - DB_ROOT_PASSWORD=admin
  
  estate-db:
    container_name: estate-db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'

# LISTING MICROSERVICE
  listing-webapi:
    container_name: listing-webapi
    image: ${DOCKER_REGISTRY-}listingWebAPI
    build:
      context: .
      dockerfile: RealEstate.API/Dockerfile #fix dir
    networks: 
      - backend 
    environment: 
      - DB_HOST=listingdb
      - DB_NAME=listings
      - DB_ROOT_PASSWORD=admin
  
  listing-db:
    container_name: listing-db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'



