name: api.external

on:
  workflow_dispatch:
  push:
    branches:
    - main

    paths:
    - Microservices/ExternalAPIsMicroservice**
    - .github/workflows/api.external.yml
  
  pull_request:
    branches:
    - main

    paths:
    - Microservices/ExternalAPIsMicroservice**
    - .github/workflows/api.external.yml

env:
  SERVICE: api.external
  IMAGE: api.external

jobs:

  BuildContainersForPR_Linux:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: ./.github/workflows/composite/build
      with:
        service: ${{ env.SERVICE }}
        registry_endpoint: ${{ secrets.REGISTRY_ENDPOINT }}